[features]
seeds = false
[programs.devnet]
nft = "HBCzpKzWESn9gHKaGvPpe84Bt66CmF1S6mbLrCBCUb5T"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/av/.config/solana/id.json"

[scripts]
test-nft = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nft.ts"
test-nftToken = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nftToken.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nft.ts"
