[features]
seeds = false
[programs.devnet]
listings = "D3544YeKkf5zB3ENMWiNR62kENQtJhkhCi2CbnruVrBi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/av/.config/solana/id.json"

[scripts]
# test-auction = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/englishAuction.ts"
test-fixed = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/fixed.ts"
