[features]
seeds = false
[programs.devnet]
memusic_nft = "DN4P41d49eZosBp6Y4cFsPPmwJFqhm4D759mrSgJGADm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/av/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
