[features]
seeds = false
[programs.localnet]
listings = "WVXjV3GziXiYjAyZJGsUdaW7RLmEeL5h57BzbvJdh2A"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/av/.config/solana/id.json"

[scripts]
test-auction-bid = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/englishAuction/bid.ts"
test-auction-bidPda = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/englishAuction/bidPda.ts"
test-auction-close = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/englishAuction/close.ts"
test-auction-listing = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/englishAuction/listing.ts"
test-auction-listingPda = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/englishAuction/listingPda.ts"
test-auction-nftListing = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/englishAuction/nftListing.ts"
test-auction-withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/englishAuction/withdraw.ts"

test-nftToken = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nftToken.ts"
test-nftTransfer = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nftTransfer.ts"

test-fixed-buy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/fixed/buy.ts"
test-fixed-close = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/fixed/close.ts"
test-fixed-listing = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/fixed/listing.ts"
test-fixed-listingPda = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/fixed/listingPda.ts"
test-fixed-nftListing = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/fixed/nftListing.ts"
