[features]
seeds = false
[programs.devnet]
listings = "68CvRsPtapjtDRNhAQTYy3iXNnofNudibfJNEj1DE3i9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/av/.config/solana/id.json"

[scripts]
test-auction = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/englishAuction.ts"
test-fixed = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/listing/fixed.ts"
